### ISSUE TITLE
一键部署无法成功，RuntimeError: Failed to access KV server. Error: 401 b'Not Authorized!'.

### ISSUE THREAD

**Issue by fatwang2** [leptonai/search_with_lepton#12]
报错日志如下
`ython3.10/site-packages (from httpx<1,>=0.23.0->openai->-r /tmp/tmpi88cdntr.txt (line 1)) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in /opt/lepton/venv/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai->-r /tmp/tmpi88cdntr.txt (line 1)) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/lepton/venv/lib/python3.10/site-packages (from pydantic<3,>=1.9.0->openai->-r /tmp/tmpi88cdntr.txt (line 1)) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in /opt/lepton/venv/lib/python3.10/site-packages (from pydantic<3,>=1.9.0->openai->-r /tmp/tmpi88cdntr.txt (line 1)) (2.14.6)
Downloading openai-1.10.0-py3-none-any.whl (225 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.1/225.1 kB 2.5 MB/s eta 0:00:00
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Installing collected packages: distro, openai
Successfully installed distro-1.9.0 openai-1.10.0
Launching photon on port: 8080
2024-01-28 03:45:50.845 | INFO     | search_with_lepton:init:267 - Creating KV. May take a while for the first time.
Failed to launch photon: <class 'RuntimeError'>: Failed to access KV server. 
Error: 401 b'Not Authorized!'.
Traceback:
Traceback (most recent call last):
  File "/opt/lepton/venv/lib/python3.10/site-packages/leptonai/cli/photon.py", 
line 785, in run
    photon.launch(port=port)
  File 
"/opt/lepton/venv/lib/python3.10/site-packages/leptonai/photon/photon.py", line 
869, in launch
    self._call_init_once()
  File 
"/opt/lepton/venv/lib/python3.10/site-packages/leptonai/photon/photon.py", line 
598, in _call_init_once
    self._init_res = self.init()
  File "/Users/jiayq/Documents/code/search_with_lepton/search_with_lepton.py", 
line 268, in init
  File "/opt/lepton/venv/lib/python3.10/site-packages/leptonai/kv.py", line 166,
in __init__
    raise RuntimeError(
RuntimeError: Failed to access KV server. Error: 401 b'Not Authorized!'.
`

**Comment by vthinkxie** [comment]
Hi, If you need to use the built-in kv, you need to log in to lepton and try "lep login". If you need to use your own kv, you need to make additional modifications to the code.

**Comment by fatwang2** [comment]
您好，我是用的一键部署，看需要 kv，就在leptonai 下面建了个同名 kv，不确定你说的需要登录指的是什么
