### ISSUE TITLE
问了一个问题后，继续提问，无法使用上下文

### ISSUE THREAD

**Issue by kyiree** [leptonai/search_with_lepton#19]
每次提问都是新的对话？没有实现上下文的机制

**Comment by Yangqing** [comment]
Yep, this is something that we intend to do later... Right now every query is new.

**Comment by HuaizhengZhang** [comment]
> Yep, this is something that we intend to do later... Right now every query is new.

Do you have any plans to release the roadmap? I am glad to contribute and use this service to our product.

**Comment by haodaohong** [comment]
自己扩展就好，我已经扩展了上下文，以及markdown渲染增加表格代码友好显示，过阵子准备开源

**Comment by fword** [comment]
> 自己扩展就好，我已经扩展了上下文，以及markdown渲染增加表格代码友好显示，过阵子准备开源

啥时候开源呀，
