### ISSUE TITLE
The frontend requests the same query twice, doubles the costs

### ISSUE THREAD

**Issue by shan-mx** [leptonai/search_with_lepton#21]
It makes the backend to call search and LLM twice, doubling the costs.

<img width="1003" alt="image" src="https://github.com/leptonai/search_with_lepton/assets/36291011/b3b90860-817d-4d17-899d-0c876ad534c8">
<img width="437" alt="image" src="https://github.com/leptonai/search_with_lepton/assets/36291011/703a22b7-6a25-4b92-b050-00bfbc2c8d1c">

**Comment by shan-mx** [comment]
I think The 'useEffect' in result.tsx executes twice and caused this bug.

**Comment by vthinkxie** [comment]
> With Strict Mode starting in React 18, whenever a component mounts in development, React will simulate immediately unmounting and remounting the component

React will always run twice in dev mode, and will only run once in prod env

https://legacy.reactjs.org/docs/strict-mode.html#ensuring-reusable-state
