### ISSUE TITLE
AI在评价政治人物时似乎存在偏见，可能与Sources引用多来自西方媒体有关

### ISSUE THREAD

**Issue by zgfAa996** [leptonai/search_with_lepton#25]

**Comment by Yangqing** [comment]
[Translation of the issue title: "The AI seems to exhibit bias when evaluating political figures, which may be related to the fact that many of the sources it references are from Western media."]

谢谢，我们的项目是一个以技术为核心的展示，旨在说明基于搜索引擎和大型语言模型的 RAG（Retrieval-Augmented Generation）技术的可行性。展示的内容由搜索引擎提供，并由大语言模型进行整合和归纳，中间不包含我们的主观观点。

我们项目的目标是技术展示，而非对任何内容进行评价或发表意见。任何基于互联网搜索结果的系统都可能会受到来源内容的影响。我们的数据来源多样，但可能会受到现有在线内容分布的影响，这并非我们项目的主观选择，而是基于互联网信息分布的现状，不代表我们对展示的观点表示同意或者反对。

Thank you. Our project is a technology-centric demonstration, aimed at illustrating the feasibility of the Retrieval-Augmented Generation (RAG) technology, which is based on search engines and large language models. The content showcased is provided by search engines and synthesized and summarized by large language models, without including our subjective opinions.

The goal of our project is to demonstrate technology, not to evaluate or express opinions on any content. Any system based on internet search results may be influenced by the content of its sources. Our data sources are diverse, but they may be affected by the current distribution of online content. This is not a subjective choice of our project, but a reflection of the state of internet information distribution and does not represent our agreement or disagreement with the viewpoints presented.
