### ISSUE TITLE
LEPTON backend has no related result

### ISSUE THREAD

**Issue by shibing624** [leptonai/search_with_lepton#40]
all the setting is default. just run with 
```
python3 search_with_lepton.py
```

<img width="783" alt="image" src="https://github.com/leptonai/search_with_lepton/assets/10249622/4fd65033-9f0f-4045-ac2b-4dafc6773293">

**Comment by Yangqing** [comment]
Sorry, we turned it off in an AB test last night and I didn't turn it back on. That was my fault. Turning it on right now.
