### ISSUE TITLE
搜索结果只用了 url、title 和 snippet 吗？

### ISSUE THREAD

**Issue by miandai** [leptonai/search_with_lepton#41]
如题，没有通过 url 抓取并解析网页内容吗？search_with_lepton.py 没看到相关实现（也可能看漏了～）

**Comment by Yangqing** [comment]
That's correct - only snippet.

You may also be able to get more information via the url - for example, crawl the page, pass it through beautifulsoup and extract the main text. We haven't implemented it and have found that snippets work fairly well as a demonstration.
