### ISSUE TITLE
为什么用 Base 模型可以实现 Chat 的效果？

### ISSUE THREAD

**Issue by SoYuCry** [leptonai/search_with_lepton#42]
我注意到 readme 中讲

LLM_MODEL: the LLM model to run. We recommend using mixtral-8x7b, but if you want to experiment other models, you can try the ones hosted on LeptonAI, for example, llama2-70b, llama2-13b, llama2-7b. Note that small models won't work that well.

为什么可以使用 Base 模型实现 Chat 效果

**Comment by Yangqing** [comment]
We are using mixtral-8x7b-instruct, sorry for the confusion. Specifically the model is this one: [mistralai/Mixtral-8x7B-Instruct-v0.1](https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1)
