### ISSUE TITLE
Start server fail saying Directory 'ui' does not exist

### ISSUE THREAD

**Issue by adrianhsm** [leptonai/search_with_lepton#43]
Error:
File "/Users/smai/workspace/ai/search_with_lepton/search_with_lepton.py", line 632, in ui
return StaticFiles(directory="ui")
FIX:
StaticFiles(directory="ui") ->StaticFiles(directory=None)

**Comment by vthinkxie** [comment]
have you built the web before run the server?

**Comment by adrianhsm** [comment]
Change directroy to None will enable server running, but access may lead to ui/index.html, then I have no idea how to prceed

**Comment by adrianhsm** [comment]
NO

**Comment by adrianhsm** [comment]
I Just clone and try to start

**Comment by adrianhsm** [comment]
where is the ui directory?

**Comment by adrianhsm** [comment]
OH, you mean I need to build the web before? ok, I see

**Comment by adrianhsm** [comment]
running ‘npm run build’ in web after clone would fix the error, make sure you have install next before hand, close issue
