### ISSUE TITLE
"Application error: a client-side exception has occurred" when rendering the answer 

### ISSUE THREAD

**Issue by aspirinj** [leptonai/search_with_lepton#51]
Failed to render the answer. The browser displayed `Application error: a client-side exception has occurred (see the browser console for more information).` error.

In the chrome console: 
```
938-fe6b19e2b7ce9569.js:1 TypeError: Failed to construct 'URL': Invalid URL
    at v (page-aa42ac90a70baa43.js:1:5723)
    at rb (fd9d1056-7fda3e9b28bca7f7.js:1:40329)
    at iU (fd9d1056-7fda3e9b28bca7f7.js:1:116116)
    at o2 (fd9d1056-7fda3e9b28bca7f7.js:1:94369)
    at fd9d1056-7fda3e9b28bca7f7.js:1:94191
    at o1 (fd9d1056-7fda3e9b28bca7f7.js:1:94198)
    at oV (fd9d1056-7fda3e9b28bca7f7.js:1:91685)
    at oB (fd9d1056-7fda3e9b28bca7f7.js:1:91110)
    at MessagePort.w (938-fe6b19e2b7ce9569.js:1:99426)
```

I checked the `result` variable in `stream_and_upload_to_kv()` method, it contains a valid string "'[{"kind": "customsearch#result", "title": "This is Why We \'Live Long and Prosper\' | Star Trek", "ht......"

My setup:
OS: windows 11
node: v18.19.0
python: 3.11.41
leptonai                          0.16.0
openai                            1.10.0

![image](https://github.com/leptonai/search_with_lepton/assets/31783844/07cf7a9c-bb14-4e65-afc7-619863239242)

**Comment by seanxuu** [comment]
same here

**Comment by chinern** [comment]
?

**Comment by Szmbbq** [comment]
Same here. `BACKEND=GOOGLE` won't work.

**Comment by seanxuu** [comment]
> Same here. `BACKEND=GOOGLE` won't work.

I think it is because the format of google's results does not match the front-end codes(BING works fine). But I can not find the solution....

**Comment by Szmbbq** [comment]
> > Same here. `BACKEND=GOOGLE` won't work.
> 
> I just find the #49 solves the problem!
> 
> Maybe you can have a try.

Thanks for sharing. Just confirmed it worked.

**Comment by aspirinj** [comment]
> > Same here. `BACKEND=GOOGLE` won't work.
> 
> I just find the #49 solves the problem!
> 
> Maybe you can have a try.

Thanks! It works with this fix. Hopefully the PR will be merged soon. Close for now.
