### ISSUE TITLE
Can not delete a "blank" kv namespace

### ISSUE THREAD

**Issue by seanxuu** [leptonai/search_with_lepton#54]
1.  I came across this problem when I tried to create a new kv namespace. It seems like a "blank" kv namespace there.

<img width="1391" alt="image" src="https://github.com/leptonai/search_with_lepton/assets/118865326/236d206f-6be3-4a68-9688-83b34ded930b">

2.  **When I tried to delete this one, I got the message:**

<img width="516" alt="image" src="https://github.com/leptonai/search_with_lepton/assets/118865326/7fdadd63-4b9c-4d21-a951-8293c56363d7">

**Comment by Yangqing** [comment]
Sorry, this is a bug in the backend, and we will fix it asap - cc @xiang90 @ccding FYI. I think we have an internal PR pending already.

**Comment by Yangqing** [comment]
https://github.com/leptonai/lepton/pull/6092 (although this is probably internal)

**Comment by ccding** [comment]
@seanxuu this should have been fixed. Please reopen the issue if you see any additional issues. Thanks for the bug report

**Comment by seanxuu** [comment]
> @seanxuu this should have been fixed. Please reopen the issue if you see any additional issues. Thanks for the bug report

Thanks a lot.  But I met another bug.

When I use google as the search engine, whether deployed in lepton or locally, it does not work. Specifically, an error is reported after the search is completed. 

I mentioned that another user reported that before: https://github.com/leptonai/search_with_lepton/issues/51

Then I check the python code and I find the error happens after this **'''yield'''** 
<img width="546" alt="image" src="https://github.com/leptonai/search_with_lepton/assets/118865326/4b1cb88c-06d9-4c43-9e2f-889a8646a9cc">

Interestingly, when I use Bing to search, it works fine. I infer that the format returned by Google may not be processed well.

**Comment by seanxuu** [comment]
> > @seanxuu this should have been fixed. Please reopen the issue if you see any additional issues. Thanks for the bug report
> 
> Thanks a lot. But I met another bug.
> 
> When I use google as the search engine, whether deployed in lepton or locally, it does not work. Specifically, an error is reported after the search is completed.
> 
> I mentioned that another user reported that before: #51
> 
> Then I check the python code and I find the error happens after this **'''yield'''** <img alt="image" width="546" src="https://private-user-images.githubusercontent.com/118865326/303567707-4b1cb88c-06d9-4c43-9e2f-889a8646a9cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NzMyMjMsIm5iZiI6MTcwNzQ3MjkyMywicGF0aCI6Ii8xMTg4NjUzMjYvMzAzNTY3NzA3LTRiMWNiODhjLTA2ZDktNGM0My05ZTJmLTg4OWE4NjQ2YTljYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxMDAyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjE1YzY4NWIxYmY1YjViMTU0YzVhM2Q0NDFiZWY2ZWMxNDE2YTYxYjBhYjgxMDMwYjQ0Y2ZhMmUyMzljZWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FolTe27F9Km7sYBsPthIcRLV8wJafMe5JNVd9b5vraw">
> 
> Interestingly, when I use Bing to search, it works fine. I infer that the format returned by Google may not be processed well.

Solved by https://github.com/leptonai/search_with_lepton/pull/49
