### ISSUE TITLE
can not delete kv namespaces

### ISSUE THREAD

**Issue by seanxuu** [leptonai/search_with_lepton#57]
![image](https://github.com/leptonai/search_with_lepton/assets/118865326/14dad4aa-b9e6-4018-ace5-d4c0557e11df)

When I try to delete the kv namespaces,I encountered the error above

**Comment by walbercardoso** [comment]
> ![image](https://private-user-images.githubusercontent.com/118865326/303584281-14dad4aa-b9e6-4018-ace5-d4c0557e11df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODg2MzksIm5iZiI6MTcwNzQ4ODMzOSwicGF0aCI6Ii8xMTg4NjUzMjYvMzAzNTg0MjgxLTE0ZGFkNGFhLWI5ZTYtNDAxOC1hY2U1LWQ0YzA1NTdlMTFkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxNDE4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTczMjZiODgzOWZlYTY3NmIzMGM3ZDM5OGI1NmU2NTdiMDFhZTFkNzM0YjAwYTY0Y2IwN2Q4NGVhZjY2NzBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ekixtyngBAJYUEUJh2SXmpk8GxduYi9EdZM8Nrs-9A4)
> 
> When I try to delete the kv namespaces,I encountered the error above

Same here

**Comment by ccding** [comment]
Confirmed it's a bug. Will fix today
